// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_9V7sfr6V5fhU3tyQhx8jd-2ndZZZpw',
    appId: '1:455349739698:web:e505367a9a5dd87dd769ab',
    messagingSenderId: '455349739698',
    projectId: 'campus-alumni',
    authDomain: 'campus-alumni.firebaseapp.com',
    storageBucket: 'campus-alumni.firebasestorage.app',
    measurementId: 'G-HGBBWFT6PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9u5j1ZzbDCxlCpZsnc65azl5DGCbzEb8',
    appId: '1:455349739698:android:9538a0c6695ac8d7d769ab',
    messagingSenderId: '455349739698',
    projectId: 'campus-alumni',
    storageBucket: 'campus-alumni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkCETCwnfx2xH_peLoipKqZZQdG8Aog0o',
    appId: '1:455349739698:ios:366e055aa68a4ad1d769ab',
    messagingSenderId: '455349739698',
    projectId: 'campus-alumni',
    storageBucket: 'campus-alumni.firebasestorage.app',
    iosBundleId: 'com.example.campusAlumni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkCETCwnfx2xH_peLoipKqZZQdG8Aog0o',
    appId: '1:455349739698:ios:366e055aa68a4ad1d769ab',
    messagingSenderId: '455349739698',
    projectId: 'campus-alumni',
    storageBucket: 'campus-alumni.firebasestorage.app',
    iosBundleId: 'com.example.campusAlumni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_9V7sfr6V5fhU3tyQhx8jd-2ndZZZpw',
    appId: '1:455349739698:web:5cc087ff84c6e93ed769ab',
    messagingSenderId: '455349739698',
    projectId: 'campus-alumni',
    authDomain: 'campus-alumni.firebaseapp.com',
    storageBucket: 'campus-alumni.firebasestorage.app',
    measurementId: 'G-DDDMR1TPRV',
  );
}
